
export const BRANCHES = [
  "B.Tech Computer Science & Engineering (CSE)",
  "B.Tech CSE (Artificial Intelligence & Machine Learning)",
  "B.Tech CSE (Data Science)",
  "B.Tech CSE (Cyber Security)",
  "B.Tech CSE (Internet of Things and Cyber Security including Blockchain Technology)",
  "B.Tech (Robotics & Artificial Intelligence)",
  "B.Tech (Artificial Intelligence & Data Science)",
  "B.Tech Civil Engineering (CE)",
  "B.Tech Electronics & Communication Engineering (ECE)",
  "B.Tech Mechanical Engineering (ME)",
  "B.Tech Mechatronics",
  "M.Tech in Computer Science & Engineering (CSE)",
  "M.Tech in Mechanical Engineering (ME)",
  "BCA (Hons)",
  "BCA (Hons) in Data Science",
  "MCA (Master of Computer Applications)",
  "BBA (Hons)",
  "BBA (Hons) in Digital Marketing",
  "BBA (Hons) in Financial Services",
  "MBA (Master of Business Administration)",
];