
export const BRANCHES = [
  "Computer Science & Engineering (CSE)",
  "Civil Engineering (CE)",
  "Electronics & Communication Engineering (ECE)",
  "Mechanical Engineering (ME)",
  "Mechatronics",
  "Robotics & Artificial Intelligence",
  "B.Tech CSE (Artificial Intelligence & Machine Learning)",
  "B.Tech (Artificial Intelligence & Data Science)",
  "B.Tech CSE (Data Science)",
  "B.Tech CSE (Cyber Security)",
  "Internet of Things and Cyber Security including Blockchain Technology",
  "M.Tech in Computer Science & Engineering (CSE)",
  "M.Tech in Mechanical Engineering (ME)",
  "BCA (Hons)",
  "BCA (Hons) in Data Science",
  "Master of Computer Applications (MCA)",
  "BBA (Hons)",
  "BBA (Hons) in Digital Marketing",
  "BBA (Hons) in Financial Services",
  "MBA (Master of Business Administration)",
];